# Generated by Django 4.1.2 on 2022-10-30 20:12

import ckeditor.fields
import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(max_length=255)),
                ('resumo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('conteudo', ckeditor_uploader.fields.RichTextUploadingField()),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='static/news/')),
                ('data_publicacao', models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 30, 20, 12, 57, 478333, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
