# Generated by Django 4.1.2 on 2022-10-30 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 30, 4, 47, 59, 43817, tzinfo=datetime.timezone.utc)),
        ),
    ]
