# Generated by Django 4.1.2 on 2022-10-26 23:17

import ckeditor.fields
import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_subtitle_post_subtitulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='static/news/'),
        ),
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 26, 23, 17, 1, 760892, tzinfo=datetime.timezone.utc)),
        ),
    ]
