# Generated by Django 4.1.2 on 2022-11-28 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_autor_postsituacao_remove_post_conteudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 28, 1, 4, 18, 592271, tzinfo=datetime.timezone.utc)),
        ),
    ]
