# Generated by Django 4.1.2 on 2022-11-17 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 17, 1, 36, 38, 410112, tzinfo=datetime.timezone.utc)),
        ),
    ]
