# Generated by Django 4.1.2 on 2022-11-17 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 17, 1, 50, 29, 166062, tzinfo=datetime.timezone.utc)),
        ),
    ]
