# Generated by Django 4.1.2 on 2022-11-26 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='situacao',
            old_name='nome',
            new_name='statussom',
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 26, 14, 0, 21, 748969, tzinfo=datetime.timezone.utc)),
        ),
    ]
