# Generated by Django 4.1.2 on 2022-11-26 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_rename_nome_situacao_statussom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='situacao',
            old_name='statussom',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 26, 14, 2, 3, 49325, tzinfo=datetime.timezone.utc)),
        ),
    ]
