# Generated by Django 4.1.2 on 2022-11-26 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_rename_statussom_situacao_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 26, 14, 43, 9, 998823, tzinfo=datetime.timezone.utc)),
        ),
    ]
