# Generated by Django 4.1.2 on 2022-11-12 18:25

import ckeditor.fields
import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipe', models.CharField(max_length=150)),
                ('foto_equipe', models.ImageField(blank=True, null=True, upload_to='static/images/torneios')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_game', models.CharField(max_length=150)),
                ('foto_game', models.ImageField(blank=True, null=True, upload_to='static/images/torneios')),
            ],
        ),
        migrations.CreateModel(
            name='Torneios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(max_length=255)),
                ('resumo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('conteudo', ckeditor_uploader.fields.RichTextUploadingField()),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='static/news/')),
                ('data_partida', models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 12, 18, 25, 4, 10482, tzinfo=datetime.timezone.utc))),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneios.game')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
