# Generated by Django 4.1.2 on 2022-11-12 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0002_equipe_game_torneios_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneios',
            name='data_partida',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 12, 18, 25, 31, 25051, tzinfo=datetime.timezone.utc)),
        ),
    ]
