# Generated by Django 4.1.2 on 2022-11-13 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0012_alter_torneios_data_partida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneios',
            name='data_partida',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 13, 22, 39, 42, 888799, tzinfo=datetime.timezone.utc)),
        ),
    ]
