# Generated by Django 4.1.2 on 2022-11-13 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0013_alter_torneios_data_partida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneios',
            name='data_partida',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 13, 22, 44, 30, 480053, tzinfo=datetime.timezone.utc)),
        ),
    ]
