# Generated by Django 4.1.2 on 2022-11-14 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0014_alter_torneios_data_partida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneios',
            name='data_partida',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 14, 2, 44, 0, 771398, tzinfo=datetime.timezone.utc)),
        ),
    ]
