# Generated by Django 4.1.2 on 2022-11-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0017_remove_torneios_data_partida_remove_torneios_resumo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipe', models.CharField(max_length=150)),
                ('foto_equipe', models.ImageField(blank=True, null=True, upload_to='static/images/torneios')),
            ],
        ),
        migrations.RenameField(
            model_name='torneios',
            old_name='imagem_capa',
            new_name='foto_torneio',
        ),
        migrations.RenameField(
            model_name='torneios',
            old_name='nome',
            new_name='nome_torneio',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='torneios',
        ),
        migrations.RemoveField(
            model_name='torneios',
            name='conteudo',
        ),
    ]
