# Generated by Django 4.1.2 on 2022-11-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0018_player_rename_imagem_capa_torneios_foto_torneio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='torneios',
            field=models.ManyToManyField(to='torneios.torneios'),
        ),
    ]
