# Generated by Django 4.1.2 on 2022-11-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0019_equipe_torneios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneios',
            name='foto_torneio',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/torneios'),
        ),
    ]
