# Generated by Django 4.1.2 on 2022-11-17 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0020_alter_torneios_foto_torneio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='torneios',
        ),
        migrations.AddField(
            model_name='equipe',
            name='toneios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torneios.torneios'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nome_equipe',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
