# Generated by Django 4.1.2 on 2022-11-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0021_remove_equipe_torneios_equipe_toneios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='toneios',
        ),
        migrations.AddField(
            model_name='equipe',
            name='toneios',
            field=models.ManyToManyField(to='torneios.torneios'),
        ),
    ]
