# Generated by Django 4.1.2 on 2022-11-17 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0024_rename_foto_equipe_player_foto_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='torneios',
        ),
    ]
