# Generated by Django 4.1.2 on 2022-11-17 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0025_remove_player_torneios'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torneios.equipe'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nome_player',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
