# Generated by Django 4.1.2 on 2022-11-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0026_player_equipe_alter_player_nome_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TorneioSituacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneios.situacao')),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneios.torneios')),
            ],
            options={
                'unique_together': {('torneio', 'situacao')},
            },
        ),
        migrations.AddField(
            model_name='situacao',
            name='torneio',
            field=models.ManyToManyField(through='torneios.TorneioSituacao', to='torneios.torneios'),
        ),
    ]
