# Generated by Django 4.1.2 on 2022-11-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0030_remove_equipe_torneios_partida_equipe_partida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='partida',
        ),
    ]
