# Generated by Django 4.1.2 on 2022-11-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0031_remove_equipe_partida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='equipe',
        ),
        migrations.AddField(
            model_name='partida',
            name='equipe',
            field=models.ManyToManyField(to='torneios.equipe'),
        ),
    ]
