# Generated by Django 4.1.2 on 2022-11-27 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0034_remove_torneios_game_alter_game_nome_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodada',
            name='Game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='torneios.game'),
            preserve_default=False,
        ),
    ]
