# Generated by Django 4.1.2 on 2022-11-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0035_rodada_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partida',
            old_name='partida',
            new_name='rodada',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='equipe',
        ),
    ]
