# Generated by Django 4.1.2 on 2022-11-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0036_rename_partida_partida_rodada_remove_partida_equipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rodada',
            old_name='Game',
            new_name='game',
        ),
        migrations.AddField(
            model_name='equipe',
            name='partida',
            field=models.ManyToManyField(to='torneios.partida'),
        ),
    ]
