# Generated by Django 4.1.2 on 2022-11-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0037_rename_game_rodada_game_equipe_partida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='partida',
        ),
        migrations.CreateModel(
            name='Equipe2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneios.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneios.equipe')),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='equipe1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='torneios.equipe1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partida',
            name='equipe2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='torneios.equipe2'),
            preserve_default=False,
        ),
    ]
