# Generated by Django 4.1.2 on 2022-11-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0038_remove_equipe_partida_equipe2_equipe1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipe1',
            old_name='equipe',
            new_name='equipe1',
        ),
        migrations.RenameField(
            model_name='equipe2',
            old_name='equipe',
            new_name='equipe2',
        ),
    ]
