# Generated by Django 4.1.2 on 2022-11-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0039_rename_equipe_equipe1_equipe1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='equipe1',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='equipe2',
        ),
        migrations.AddField(
            model_name='equipe1',
            name='partida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='torneios.partida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipe2',
            name='partida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='torneios.partida'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='equipe1',
            unique_together={('equipe1', 'partida')},
        ),
        migrations.AlterUniqueTogether(
            name='equipe2',
            unique_together={('equipe2', 'partida')},
        ),
    ]
