# Generated by Django 4.1.2 on 2022-11-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0040_remove_partida_equipe1_remove_partida_equipe2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe1',
            name='resultado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='equipe1',
            name='score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='equipe2',
            name='resultado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='equipe2',
            name='score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
