# Generated by Django 4.1.2 on 2022-11-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0041_equipe1_resultado_equipe1_score_equipe2_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe1',
            name='resultado',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='equipe2',
            name='resultado',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
