# Generated by Django 4.1.2 on 2022-11-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0042_alter_equipe1_resultado_alter_equipe2_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
